blank_issues_enabled: false
contact_links:
  - name: Trades Today Documentation
    url: https://github.com/TDA/trades-today-issues#readme
    about: Read the README for more information about Trades Today and how to report issues.
